### ISSUE TITLE
grid does not have labels on 4 hours scale AGAIN

### ISSUE THREAD

**Issue by rybafish** [rybafish/rybafish#866]

**Comment by rybafish** [comment]
Seems python datetime object has implicit timezone that needs to be considered when zoomed out to 4*hour level.

KPI to test
```yaml
kpis: [
    {type: 'service',
        name: 'tdata',
        sqlname: 'value',
        color: '#0D0',
        nofilter: true,
        label: 'test data'
        },
    ]

sql: >
    select 
        ts time,
        value
    from test_data
```

Data to test:


```sql
truncate table test_data;

create column table test_data (
    ts timestamp,
    value    integer
);

insert into test_data values('2023-09-01 00:00:01', 0);
insert into test_data values('2023-09-01 02:00:00', 10);
insert into test_data values('2023-09-01 04:00:00', 10);
insert into test_data values('2023-09-01 06:00:00', 30);
insert into test_data values('2023-09-01 08:00:00', 30);
insert into test_data values('2023-09-01 10:00:00', 20);
insert into test_data values('2023-09-01 12:00:00', 60);
insert into test_data values('2023-09-01 23:59:59', 60);

insert into test_data values('2023-09-02 00:00:00', 0);
insert into test_data values('2023-09-02 02:00:00', 10);
insert into test_data values('2023-09-02 04:00:00', 20);
insert into test_data values('2023-09-02 06:00:00', 30);
insert into test_data values('2023-09-02 08:00:00', 40);
insert into test_data values('2023-09-02 10:00:00', 50);
insert into test_data values('2023-09-02 12:00:00', 60);

commit;

```
